name: "CI Unit Test and SonarQube code_quality"

on:
  push:
    branches: [ feature/*, fix/*, demo/*, main ]
  workflow_call:
    inputs:
        workflow:
            default: "CI unit-test and SonarQube workflow is called"
            description: "calling unit-test and SonarQube workflow"
            required: false
            type: string

jobs:
  ci_unit_test:
    name: Tests with pytest
    uses: sede-x/HyperAutomation-ChangeManagement/.github/workflows/unit-test-gate-python.yaml@0.6.1
    with:
        use-pytest: true
        python-version: "3.11.x"
        python-requirements: "requirements.txt"
        test-args: "--pyargs edp_auto_loader --ignore=conftest.py --ignore=setup.py -s"
    secrets:
        # ! Threshold of coverage percentage which will be used to determine if the CI is successful or not!
        # ! This won't take a place as for Shell Sonar way locked it to minimum 80%, it's required tho.
        TEST_COVERAGE: "10"

  ci_sonarqube_code_quality:
    runs-on: ubuntu-latest
    needs: ci_unit_test
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Get branch name
        id: branch_name
        run: |
            if [[ ${{ github.ref }} == refs/heads/* ]]; then
                echo "branch=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
            else
                echo "branch=main" >> $GITHUB_OUTPUT
            fi
      - name: SonarQube Quality Gate
        uses: sede-x/HyperAutomation-ChangeManagement/.github/actions/sonarqube-gate@main
        with:
            args-branch: ${{ steps.branch_name.outputs.branch }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            sonar-unittest-args: >
                -Dsonar.projectKey=com.shell.DATTA-AUTOLOADER-MINERVA
                -Dsonar.projectName=DATTA-AUTOLOADER-MINERVA
                -Dsonar.token=${{ secrets.SONAR_TOKEN }}
                -Dsonar.sonar.host.url=${{ secrets.SONAR_HOST_URL }}
                -Dsonar.python.coverage.reportPaths=coverage.xml
